### ISSUE TITLE
Citizen - Fault status missing on ticket view

### ISSUE THREAD

**Issue by MatthewEls** [COS301-SE-2024/MyCity#588]

**Comment by MatthewEls** [comment]
Can't see current status of fault.  Is someone working on it?  Has the municipality not even acknowledged fault yet!

**Comment by MatthewEls** [comment]
Timestamps and status updates are an absolute must.  So are stats which can be easily presented to the users.

**Comment by Dindosss** [comment]
Wait what do mean, Cause ticket shows the status of the ticket its just theres only 3 states it can be in
