### ISSUE TITLE
Citizen - Adding a fault does not add it to the users faultlist by default

### ISSUE THREAD

**Issue by MatthewEls** [COS301-SE-2024/MyCity#592]
When a users creates a fault it should also get added to their watch list by default

**Comment by MatthewEls** [comment]
The fault I had just added didn't appear in my watchlist.  This seems odd as I would want to see the status of a fault I logged regularly.

**Comment by Dindosss** [comment]
starting this today by tonight should be working

**Comment by Dindosss** [comment]
its fully integrated
